CREATE TABLE worker (
ID BIGINT PRIMARY KEY,
NAME VARCHAR(1000),
CHECK(LENGTH(NAME) >= 2 AND LENGTH(NAME) <= 1000 AND NAME IS NOT NULL),
BIRTHDAY INT,
CHECK(BIRTHDAY >1900),
LEVEL VARCHAR(100),
CHECK(LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior') AND LEVEL IS NOT NULL),
SALARY INT,
CHECK(SALARY > 100 AND SALARY < 100000)
);

CREATE TABLE client (
ID BIGINT PRIMARY KEY,
CLIENT_ID INT,
START_DATE INT,
FINISH_DATE INT
);

CREATE TABLE project (
ID BIGINT PRIMARY KEY,
CLIENT_ID INT,
START_DATE DATE,
FINISH_DATE DATE
);


CREATE TABLE project_worker (
PROJECT_ID BIGINT,
WORKER_ID BIGINT,
FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID),
FOREIGN KEY (WORKER_ID) REFERENCES WORKER(ID),
PRIMARY KEY (PROJECT_ID, WORKER_ID)
);